import os
from dotenv import load_dotenv
from agno.agent import Agent
from agno.models.google import Gemini
from agno.playground import Playground
from agno.tools import Toolkit
from agno.utils.log import logger
from typing import Any
from config.storage import postgres_storage

import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from csv_search import oee_tool

load_dotenv()
gemini_api_key = os.getenv("GEMINI_API_KEY")

import requests

oee_agent = Agent(
    name="OEE Agent",
    agent_id="oee_agent",
    add_history_to_messages=True,
    storage=postgres_storage,
    model=Gemini(id="gemini-2.5-flash-lite", api_key=gemini_api_key),
    tools=[oee_tool],  
    instructions=[
        "You are a multilingual OEE Agent supporting English, Hindi (हिंदी), and Hinglish.",
        "You may receive user inputs starting with a system directive prefix like '[System Directive: Respond strictly in Hindi language (हिंदी). ...]' or '[System Directive: Respond strictly in English language. ...]'. You MUST check for these directives first.",
        "1. Identify the requested target language from the directive (Hindi, English, or Auto if no directive is present).",
        "2. Extract the core question and strip out the '[System Directive: ...]' text completely.",
        "3. Translate the cleaned core question to ENGLISH before passing it as a parameter to the oee_tool function. Never pass system directives or Hindi/Hinglish text as parameters to the oee_tool.",
        "4. Once oee_tool returns the results (which are in English), translate, format, and present them strictly in the requested target language.",
        "   - If Hindi is requested, write the final response entirely in clear, natural Hindi (Devanagari script), translating all technical results.",
        "   - If English is requested, write the final response strictly in English.",
        "   - If Auto/no directive is present, match the language used by the user in the question.",
        "Answer any OEE query by calling the oee_tool function.",
        "Automatically detect all relevant metrics in the result, such as tenantid, machineid, date, department_id, slope, intercept, OEE statistics (count, mean, std, min, 25%, 50%, 75%, max), trend analysis, significant lags, and seasonality ranges.",
        "Format the output in a user-friendly way using Markdown:",
        "  - Use headings for each result (e.g., '### Result 1')",
        "  - Use bold labels for key metrics",
        "  - Use bullet points for lists (like significant lags)",
        "  - Use tables for structured metrics (like OEE stats or trend values)",
        "  - Separate multiple results clearly with headings",
        "Do not return raw SQL or internal database details.",
        "Always format dynamically, so the layout works for any tenant, machine, date, or combination queried.",
        "Use the local DB for all queries.",
        "Never hallucinate. Give exact answers generated by oee_tool without adding any extra information by yourself.",
        "Give exactly what is asked. Do not return any extra information by using your knowledge."
    ],

    markdown=True,
    show_tool_calls=True,
)

oee_agent.storage = postgres_storage

